name: microservices

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
    networks:
      - microservices-network
  
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - microservices-network
  
  users-api:
    image: users-api
    container_name: users-api
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8084
      - JWT_SECRET=PRFT
      - ZIPKIN_URL=http://zipkin:9411/
    depends_on:
      - zipkin
    networks:
      - microservices-network
  
  auth-api:
    image: auth-api
    container_name: auth-api
    ports:
      - 8000:8000
    environment:
      - AUTH_API_PORT=8000
      - JWT_SECRET=PRFT
      - USERS_API_ADDRESS=http://users-api:8084
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - users-api
    networks:
      - microservices-network
  
  todos-api:
    image: todos-api
    container_name: todos-api
    ports:
      - 8082:8082
    environment:
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - redis
      - zipkin
    networks:
      - microservices-network
  
  log-message-processor:
    image: log-message-processor
    container_name: log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - redis
      - zipkin
    networks:
      - microservices-network
  
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - auth-api
      - users-api
      - todos-api
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
