- name: Install Docker Engine, Compose Plugin, and Authenticate with ACR
  hosts: app
  become: true

  vars:
    repo_clone_url: ""
    repo_branch: "main"
    acr_login_server: ""

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - git
          - apt-transport-https
          - lsb-release
        state: present
        update_cache: true

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: yes

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch="{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}" signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: yes

    - name: Install Docker and Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Azure CLI
      shell: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | bash

    - name: Login to Azure using Managed Identity
      shell: az login --identity

    - name: Authenticate Docker with ACR using Azure CLI
      shell: az acr login --name "{{ acr_login_server.split('.')[0] }}"

    - name: Clone infrastructure repository
      git:
        repo: "{{ repo_clone_url }}"
        dest: /home/{{ ansible_user }}/infrastructure
        version: "{{ repo_branch }}"
        force: yes
      become: false