---
- name: Install docker in virtual machine
  hosts: app
  become: true

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Ensure permissions for the Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'
