services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - mynetwork
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
    networks:
      - mynetwork
  users-api:
    image: ${IMAGE_REGISTRY}/users-api:${IMAGE_TAG}
    container_name: users-api
    ports:
      - 8083:8083
    volumes:
      - users_data:/app/data
    depends_on:
      - zipkin
    networks:
      - mynetwork
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
      - ZIPKIN_URL=http://zipkin:9411/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  auth-api:
    image: ${IMAGE_REGISTRY}/auth-api:${IMAGE_TAG}
    container_name: auth-api
    ports:
      - 8000:8000
    depends_on:
      - users-api
      - zipkin
    networks:
      - mynetwork
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  todos-api:
    image: ${IMAGE_REGISTRY}/todos-api:${IMAGE_TAG}
    container_name: todos-api
    ports:
      - 8082:8082
    depends_on:
      - redis
      - zipkin
    networks:
      - mynetwork
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend:
    image: ${IMAGE_REGISTRY}/frontend:${IMAGE_TAG}
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - api-gateway
      - zipkin
    networks:
      - mynetwork
    environment:
      - AUTH_API_ADDRESS=http://api-gateway:8090/auth
      - TODOS_API_ADDRESS=http://api-gateway:8090/todos
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
  log-message-processor:
    image: ${IMAGE_REGISTRY}/log-message-processor:${IMAGE_TAG}
    container_name: log-message-processor
    depends_on:
      - redis
      - zipkin
    networks:
      - mynetwork
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
  api-gateway:
    image: ${IMAGE_REGISTRY}/api-gateway:${IMAGE_TAG}
    container_name: api-gateway
    ports:
      - 8090:8090
    depends_on:
      - auth-api
      - todos-api
    networks:
      - mynetwork
    environment:
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
networks:
  mynetwork:
    driver: bridge
volumes:
  cache:
    driver: local
  users_data:
    driver: local