name: Destroy Container Apps Infrastructure
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_location: 'East US'
      TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
      TF_VAR_acr_name: ${{ secrets.ACR_NAME }}
      TF_VAR_key_vault_name: ${{ secrets.KEY_VAULT_NAME }}
      TF_VAR_image_tag: 'latest'
      TF_VAR_prefix: 'microservice'
    defaults:
      run:
        working-directory: terraform/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Remove Secrets from Key Vault
        run: |
          # Delete all the service-related secrets we created
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name acr-login-server
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name frontend-url
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name api-gateway-url
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name container-app-domain
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name zipkin-url
          az keyvault secret delete --vault-name ${{ secrets.KEY_VAULT_NAME }} --name redis-hostname
        continue-on-error: true

      - name: Azure Logout
        run: az logout
